version: '3.8'

services:
    redis:
        container_name: ${SERVICE}-redis
        image: redis:latest
        restart: unless-stopped
        tty: true
        command: redis-server --appendonly yes
        volumes:
            - donors_redis:/data
        networks:
            - infrastructure

    db:
        container_name: ${SERVICE}-db
        image: postgres:latest
        restart: unless-stopped
        tty: true
        environment:
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_MAX_CONNECTIONS: ${POSTGRES_MAX_CONNECTIONS}
        volumes:
            - donors_db:/var/lib/postgresql/data
            - donors_db:/docker-entrypoint-initdb.d
        networks:
            - infrastructure

volumes:
    donors_redis: {}
    donors_db: {}

networks:
    infrastructure:
        name: ${SERVICE}_donors_infrastructure
        driver: bridge

    donors_infrastructure:
        name: donors_infrastructure
        driver: bridge
